-- drop database mydb;
-- MySQL Script generated by MySQL Workbench
-- 06/01/18 15:17:33
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CONTRATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONTRATO` (
  `id_contrato` INT NOT NULL AUTO_INCREMENT,
  `sueldo` INT NULL,
  `horario` VARCHAR(45) NULL,
  `afp` INT NULL,
  `salud` INT NULL,
  PRIMARY KEY (`id_contrato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RRHH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RRHH` (
  `run` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido_p` VARCHAR(45) NULL,
  `apellido_m` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `id_contrato` INT NOT NULL,
  PRIMARY KEY (`run`),
  INDEX `fk_RRHH_CONTRATO_idx` (`id_contrato` ASC),
  CONSTRAINT `fk_RRHH_CONTRATO`
    FOREIGN KEY (`id_contrato`)
    REFERENCES `mydb`.`CONTRATO` (`id_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAIS` (
  `id_pais` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DIRECCION` (
  `id_direccion` INT NOT NULL,
  `calle` VARCHAR(45) NULL,
  `sector` VARCHAR(45) NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `fk_DIRECCION_PAIS1_idx` (`id_pais` ASC),
  CONSTRAINT `fk_DIRECCION_PAIS1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `mydb`.`PAIS` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DEPARTAMENTO` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `tipo_depto` VARCHAR(45) NULL,
  `nombre_depto` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `id_direccion` INT NOT NULL,
  PRIMARY KEY (`id_departamento`),
  INDEX `fk_DEPARTAMENTO_DIRECCION1_idx` (`id_direccion` ASC),
  CONSTRAINT `fk_DEPARTAMENTO_DIRECCION1`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `mydb`.`DIRECCION` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OFICINA_PARTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OFICINA_PARTES` (
  `id_oficinapartes` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `categorias` VARCHAR(45) NULL,
  `id_direccion` INT NOT NULL,
  PRIMARY KEY (`id_oficinapartes`),
  INDEX `fk_OFICINA_PARTES_DIRECCION1_idx` (`id_direccion` ASC),
  CONSTRAINT `fk_OFICINA_PARTES_DIRECCION1`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `mydb`.`DIRECCION` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CARGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CARGO` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nombre_cargo` VARCHAR(45) NULL,
  `id_contrato` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  `id_oficinapartes` INT NOT NULL,
  PRIMARY KEY (`id_cargo`),
  INDEX `fk_CARGO_CONTRATO1_idx` (`id_contrato` ASC),
  INDEX `fk_CARGO_DEPARTAMENTO1_idx` (`id_departamento` ASC),
  INDEX `fk_CARGO_OFICINA_PARTES1_idx` (`id_oficinapartes` ASC),
  CONSTRAINT `fk_CARGO_CONTRATO1`
    FOREIGN KEY (`id_contrato`)
    REFERENCES `mydb`.`CONTRATO` (`id_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARGO_DEPARTAMENTO1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`DEPARTAMENTO` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARGO_OFICINA_PARTES1`
    FOREIGN KEY (`id_oficinapartes`)
    REFERENCES `mydb`.`OFICINA_PARTES` (`id_oficinapartes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROFESION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROFESION` (
  `id_profesion` INT NOT NULL AUTO_INCREMENT,
  `nombre_profesion` VARCHAR(45) NULL,
  `año_egreso` VARCHAR(45) NULL,
  `area_profesion` VARCHAR(45) NULL,
  `id_cargo` INT NOT NULL,
  PRIMARY KEY (`id_profesion`),
  INDEX `fk_PROFESION_CARGO1_idx` (`id_cargo` ASC),
  CONSTRAINT `fk_PROFESION_CARGO1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `mydb`.`CARGO` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RRHH_DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RRHH_DIRECCION` (
  `run` INT NOT NULL,
  `id_direccion` INT NOT NULL,
  PRIMARY KEY (`run`, `id_direccion`),
  INDEX `fk_RRHH_has_DIRECCION_DIRECCION1_idx` (`id_direccion` ASC),
  INDEX `fk_RRHH_has_DIRECCION_RRHH1_idx` (`run` ASC),
  CONSTRAINT `fk_RRHH_has_DIRECCION_RRHH1`
    FOREIGN KEY (`run`)
    REFERENCES `mydb`.`RRHH` (`run`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RRHH_has_DIRECCION_DIRECCION1`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `mydb`.`DIRECCION` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CASA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CASA` (
  `id_casa` INT NOT NULL,
  `numero_casa` INT NULL,
  `id_direccion` INT NOT NULL,
  PRIMARY KEY (`id_casa`),
  INDEX `fk_CASA_DIRECCION1_idx` (`id_direccion` ASC),
  CONSTRAINT `fk_CASA_DIRECCION1`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `mydb`.`DIRECCION` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DEPT_HOGAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DEPT_HOGAR` (
  `id_depto_hogar` INT NOT NULL,
  `numero_depto` INT NULL,
  `numero_piso` INT NULL,
  `id_direccion` INT NOT NULL,
  PRIMARY KEY (`id_depto_hogar`),
  INDEX `fk_DEPT_HOGAR_DIRECCION1_idx` (`id_direccion` ASC),
  CONSTRAINT `fk_DEPT_HOGAR_DIRECCION1`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `mydb`.`DIRECCION` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REGION`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `REGION` (
  `region_id` int(11) NOT NULL AUTO_INCREMENT,
  `region_nombre` varchar(64) NOT NULL,
  `region_ordinal` varchar(4) NOT NULL,
    `id_pais` INT NOT NULL,
  PRIMARY KEY (`region_id`), 
  INDEX `fk_REGION_PAIS1_idx` (`id_pais` ASC),
  CONSTRAINT `fk_REGION_PAIS1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `mydb`.`PAIS` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;






CREATE TABLE `COMUNA` (
  `id_comuna` int(11) NOT NULL AUTO_INCREMENT,
  `comuna_nombre` varchar(64) NOT NULL,
  `id_provincia` int(11) NOT NULL,
FOREIGN KEY (`id_provincia`) REFERENCES provincia(`id_provincia`),
  PRIMARY KEY (`id_comuna`)
) ;





-- -----------------------------------------------------
-- Table `mydb`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provincia` (
  `id_provincia` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `id_region` INT NOT NULL,
  PRIMARY KEY (`id_provincia`),
    FOREIGN KEY (`id_region`)REFERENCES `mydb`.`REGION` (`id_region`));


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `id_usuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `run` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_USUARIO_RRHH1_idx` (`run` ASC),
  CONSTRAINT `fk_USUARIO_RRHH1`
    FOREIGN KEY (`run`)
    REFERENCES `mydb`.`RRHH` (`run`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOCUMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DOCUMENTOS` (
  `folio` INT NOT NULL,
  `nombre_documento` VARCHAR(45) NULL,
  `id_departamento` INT NOT NULL,
  `id_oficinapartes` INT NOT NULL,
  PRIMARY KEY (`folio`),
  INDEX `fk_DOCUMENTOS_DEPARTAMENTO1_idx` (`id_departamento` ASC),
  INDEX `fk_DOCUMENTOS_OFICINA_PARTES1_idx` (`id_oficinapartes` ASC),
  CONSTRAINT `fk_DOCUMENTOS_DEPARTAMENTO1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`DEPARTAMENTO` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCUMENTOS_OFICINA_PARTES1`
    FOREIGN KEY (`id_oficinapartes`)
    REFERENCES `mydb`.`OFICINA_PARTES` (`id_oficinapartes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADJUNTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADJUNTOS` (
  `id_adjunto` INT AUTO_INCREMENT,
  `folio` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_recepcion` VARCHAR(45) NULL,
  `destinatario` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `fecha_envio` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_adjunto`),
  INDEX `fk_DOCUMENTOS_has_USUARIO_USUARIO1_idx` (`id_usuario` ASC),
  INDEX `fk_DOCUMENTOS_has_USUARIO_DOCUMENTOS1_idx` (`folio` ASC),
  CONSTRAINT `fk_DOCUMENTOS_has_USUARIO_DOCUMENTOS1`
    FOREIGN KEY (`folio`)
    REFERENCES `mydb`.`DOCUMENTOS` (`folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCUMENTOS_has_USUARIO_USUARIO1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
